server:
  port: 3000
spring:
  application:
    name: "pan-server"
  datasource: # 数据库配置
    dynamic:
      primary: postgres # 设置默认的数据源或者数据源组,默认值即为master
      strict: false # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        base_gis:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://feihu1024.cn:5432/base_gis?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
          username: postgres
          password: 123456pro
          type: com.alibaba.druid.pool.DruidDataSource
        postgres:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/postgres
          username: postgres
          password: 123456
          type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# Mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL语句
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false
    auto-mapping-behavior: full # 自动映射resultMap

# ftpserver配置
ftp:
  port: 3100
  passivePorts: 3200-3300
  # passiveExternalAddress: 127.0.0.1

# Swagger-ui配置
swagger:
  enable: true
  basePackage: "com.feihu1024.panserver.controller"
  application-name: ${spring.application.name}
  application-version: "0.0.1"
  title: "pan-server接口文档"
  application-description: "个人网盘系统接口文档"
  contact: "feihu1024"